// Unit test sketch for G711Encoder.
//
// STATUS: placeholder. Will exercise the encoder against the reference
// table generated by tests/tools/gen_test_audio.py once the encoder
// implementation lands. For now this just confirms the sketch links
// against the library.

#include <PCMFlowG711.h>

void setup()
{
    Serial.begin(115200);
    delay(2000);
    Serial.println("TEST start g711_encoder");
    Serial.println("TEST done 0/0");
}

void loop()
{
    delay(1);
}
