#!/usr/bin/env python3
"""Generate G.711 encode/decode reference tables for the test fixtures.

The G.711 algorithm is defined by ITU-T Recommendation G.711. The
encode/decode mappings are deterministic, so this script produces the
reference tables straight from the specification, without depending on
any third-party codec (ffmpeg, sox, etc.). The resulting tables are
embedded as C arrays under each test's `input/` directory and asserted
bit-exactly by the on-device sketches.

Usage:
    python gen_test_audio.py                # writes all fixtures
    python gen_test_audio.py --print-table  # prints tables to stdout

The mu-law / A-law formulas below come from the ITU-T G.711
specification; this is an independent implementation of the published
mathematical mapping, not derived from any third-party source code.
"""

from __future__ import annotations

import argparse
import pathlib

# -------------------------------------------------------------------- mu-law

# ITU-T G.711 Annex 1: mu = 255.
_MULAW_BIAS = 0x84  # 132
_MULAW_CLIP = 32635


def mulaw_encode_sample(pcm16: int) -> int:
    """Encode one 16-bit signed PCM sample to a mu-law byte (0..255)."""
    sign = 0
    if pcm16 < 0:
        pcm16 = -pcm16
        sign = 0x80
    if pcm16 > _MULAW_CLIP:
        pcm16 = _MULAW_CLIP
    pcm16 += _MULAW_BIAS
    seg = 7
    mask = 0x4000
    while (pcm16 & mask) == 0 and seg > 0:
        mask >>= 1
        seg -= 1
    mantissa = (pcm16 >> (seg + 3)) & 0x0F
    code = ~(sign | (seg << 4) | mantissa) & 0xFF
    return code


def mulaw_decode_sample(code: int) -> int:
    """Decode one mu-law byte to a 16-bit signed PCM sample."""
    code = ~code & 0xFF
    sign = code & 0x80
    seg = (code >> 4) & 0x07
    mantissa = code & 0x0F
    magnitude = ((mantissa << 3) + _MULAW_BIAS) << seg
    magnitude -= _MULAW_BIAS
    return -magnitude if sign else magnitude


# -------------------------------------------------------------------- A-law

_ALAW_INVERT = 0x55


def alaw_encode_sample(pcm16: int) -> int:
    if pcm16 >= 0:
        sign = 0x80
    else:
        sign = 0x00
        pcm16 = -pcm16 - 1
    if pcm16 > 32767:
        pcm16 = 32767
    if pcm16 < 256:
        seg = 0
        mantissa = (pcm16 >> 4) & 0x0F
    else:
        seg = 1
        v = pcm16 >> 4
        while v >= 32:
            v >>= 1
            seg += 1
        mantissa = (pcm16 >> (seg + 3)) & 0x0F
    code = (sign | (seg << 4) | mantissa) ^ _ALAW_INVERT
    return code & 0xFF


def alaw_decode_sample(code: int) -> int:
    code ^= _ALAW_INVERT
    sign = code & 0x80
    seg = (code >> 4) & 0x07
    mantissa = code & 0x0F
    if seg == 0:
        magnitude = (mantissa << 4) + 8
    else:
        magnitude = ((mantissa << 4) + 0x108) << (seg - 1)
    return magnitude if sign else -magnitude


# -------------------------------------------------------------------- fixtures


_BANNER = (
    "// Auto-generated by tests/tools/gen_test_audio.py — do not edit.\n"
    "// Source of truth: ITU-T G.711 specification, reproduced independently in\n"
    "// the generator script. Regenerate by running:\n"
    "//     python tests/tools/gen_test_audio.py\n"
)


def _fmt_u8_row(values, per_row=16):
    return ",\n    ".join(
        ", ".join(f"0x{v:02X}" for v in values[i : i + per_row])
        for i in range(0, len(values), per_row)
    )


def _fmt_i16_row(values, per_row=8):
    return ",\n    ".join(
        ", ".join(f"{v:6d}" for v in values[i : i + per_row])
        for i in range(0, len(values), per_row)
    )


def write_decoder_reference(path: pathlib.Path) -> None:
    """All 256 byte values -> decoded PCM, for both variants."""
    mu = [mulaw_decode_sample(c) for c in range(256)]
    a = [alaw_decode_sample(c) for c in range(256)]
    body = (
        f"{_BANNER}"
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        "// 256-entry decode reference tables, one PCM sample per input byte.\n"
        "static const int16_t kG711MuLawDecodeRef[256] = {\n"
        f"    {_fmt_i16_row(mu)}\n"
        "};\n\n"
        "static const int16_t kG711ALawDecodeRef[256] = {\n"
        f"    {_fmt_i16_row(a)}\n"
        "};\n"
    )
    path.write_text(body, encoding="utf-8")


def write_encoder_reference(path: pathlib.Path) -> None:
    """Sampled PCM inputs and their expected mu-law / A-law encodings.

    Strategy: sweep the full 16-bit signed range with a fine-enough step
    that every segment boundary is exercised at least once. Step = 17
    yields 3856 samples — small enough to embed (~12 KB Flash) but dense
    enough to catch any off-by-one in the segment calculator.
    """
    step = 17
    samples = list(range(-32768, 32768, step))
    mu = [mulaw_encode_sample(s) for s in samples]
    a = [alaw_encode_sample(s) for s in samples]
    body = (
        f"{_BANNER}"
        "#pragma once\n"
        "#include <stdint.h>\n"
        "#include <stddef.h>\n\n"
        f"static const size_t kG711EncodeRefCount = {len(samples)};\n\n"
        "static const int16_t kG711EncodeRefPcm[] = {\n"
        f"    {_fmt_i16_row(samples)}\n"
        "};\n\n"
        "static const uint8_t kG711EncodeRefMuLaw[] = {\n"
        f"    {_fmt_u8_row(mu)}\n"
        "};\n\n"
        "static const uint8_t kG711EncodeRefALaw[] = {\n"
        f"    {_fmt_u8_row(a)}\n"
        "};\n"
    )
    path.write_text(body, encoding="utf-8")


def write_roundtrip_reference(path: pathlib.Path) -> None:
    """PCM inputs and the values they should decode to after encode->decode.

    Because G.711 is lossy, this is NOT input == output. The expected
    value for each input is what the spec mapping produces when the
    sample is encoded then decoded. Stored as a side-by-side table so
    the on-device test can assert bit-exactly.
    """
    # Cover boundaries of each segment plus the dense interior.
    samples = []
    samples.extend(range(-32768, -32000, 1))
    samples.extend(range(-32000, 32000, 251))    # sweep with a stride coprime to segment width
    samples.extend(range(32000, 32768, 1))
    mu_expected = [mulaw_decode_sample(mulaw_encode_sample(s)) for s in samples]
    a_expected = [alaw_decode_sample(alaw_encode_sample(s)) for s in samples]
    body = (
        f"{_BANNER}"
        "#pragma once\n"
        "#include <stdint.h>\n"
        "#include <stddef.h>\n\n"
        f"static const size_t kG711RoundtripCount = {len(samples)};\n\n"
        "static const int16_t kG711RoundtripPcm[] = {\n"
        f"    {_fmt_i16_row(samples)}\n"
        "};\n\n"
        "static const int16_t kG711RoundtripMuLaw[] = {\n"
        f"    {_fmt_i16_row(mu_expected)}\n"
        "};\n\n"
        "static const int16_t kG711RoundtripALaw[] = {\n"
        f"    {_fmt_i16_row(a_expected)}\n"
        "};\n"
    )
    path.write_text(body, encoding="utf-8")


# -------------------------------------------------------------------- driver


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--print-table",
        action="store_true",
        help="Print the 256-entry decode tables for both variants and exit.",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()
    if args.print_table:
        for name, fn in [("mu", mulaw_decode_sample), ("A", alaw_decode_sample)]:
            print(f"# {name}-law decode table (256 entries, 16-bit signed):")
            for c in range(256):
                print(f"  {c:3d} -> {fn(c):+6d}")
        return

    tests_root = pathlib.Path(__file__).resolve().parents[1]
    targets = {
        "g711_decoder": ("reference.h", write_decoder_reference),
        "g711_encoder": ("reference.h", write_encoder_reference),
        "roundtrip":    ("reference.h", write_roundtrip_reference),
    }
    for sub, (name, fn) in targets.items():
        out_dir = tests_root / sub / "input"
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / name
        fn(out_path)
        print(f"wrote {out_path.relative_to(tests_root)}")


if __name__ == "__main__":
    main()
