/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef PCMFLOWG711_VERSION_H
#define PCMFLOWG711_VERSION_H

#define PCMFLOWG711_VERSION_MAJOR 0
#define PCMFLOWG711_VERSION_MINOR 1
#define PCMFLOWG711_VERSION_PATCH 0
#define PCMFLOWG711_VERSION_STR "0.1.0"

#endif // PCMFLOWG711_VERSION_H
