// Unit test sketch for G711Decoder.
//
// STATUS: placeholder. Will exercise all 256 input byte values against
// the reference decode table generated by tests/tools/gen_test_audio.py
// once the decoder implementation lands.

#include <PCMFlowG711.h>

void setup()
{
    Serial.begin(115200);
    delay(2000);
    Serial.println("TEST start g711_decoder");
    Serial.println("TEST done 0/0");
}

void loop()
{
    delay(1);
}
